---
title: "lockdown risk analysis"
author: "Tiffany Wan"
date: "2026-04-17"
output: html_document
---

## load library

```{r load library}
library(tidyverse)
library(data.table)
library(janitor)
library(viridis)
library(ape)
library(ggtree)
library(data.table)
library(tidyverse)
library(phytools)
library(pscl)
library(lmerTest)
library(purrr)
```



# variant call results including gubbins and MLtree files
```{r, echo=FALSE,fig.show='hide'}
# read variant calling results
var_call_dirs <- list.files("data/var_call/",full.names = TRUE)
fasta_ls <- lapply(var_call_dirs, function(dir){
  read.FASTA(dir, type = "DNA")
})
names(fasta_ls) <- c("ST131","ST10","ST1598","ST1722","ST38","ST46","ST636","ST69","ST757")
fasta_ls[["ST131"]] <- fasta_ls[["ST131"]][names(fasta_ls[["ST131"]]) != "NZ_UFZF01000006.1"]

#131
Ecoli_131 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_01_12_IMPALA_variant_calling/Ecoli/EcoliST131/2024_02_29_15_04_03_core_results/gubbins/2024_02_29_15_04_03_Ecoli_NCTC13441_ST131_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")
# NZ_UFZF01000006.1

#10
Ecoli_10 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST10/2024_03_26_14_44_48_core_results/gubbins/2024_03_26_14_44_48_ST10_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")

#1598
Ecoli_1598 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST1598/2024_03_26_14_46_44_core_results/gubbins/2024_03_26_14_46_44_ST1598_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")

#1722
Ecoli_1722 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST1722/2024_03_26_14_48_41_core_results/gubbins/2024_03_26_14_48_41_ST1722_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")

#38
Ecoli_38 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST38/2024_03_26_14_50_41_core_results/gubbins/2024_03_26_14_50_41_ST38_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")

#46
Ecoli_46 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST46/2024_03_26_14_52_18_core_results/gubbins/2024_03_26_14_52_18_ST46_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")

#636
Ecoli_636 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST636/2024_03_26_14_54_51_core_results/gubbins/2024_03_26_14_54_51_ST636_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")

#69
Ecoli_69 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST69/2024_03_26_14_59_18_core_results/gubbins/2024_03_26_14_59_18_ST69_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")

#757
Ecoli_757 <- read.FASTA("/Users/tifwan/Desktop/flux_mount_gl/Project_IMPALA/old_Sequence_data/output_files/2024_03_21_Ecoli_ST_based_variant_calling/ST757/2024_03_26_15_01_22_core_results/gubbins/2024_03_26_15_01_22_ST757_genome_aln_w_alt_allele_unmapped.filtered_polymorphic_sites.fasta", type = "DNA")
# outgroup =IMPALA_43
```

# create distance matrices from variant calling
```{r}
var_call_dist_ls <- lapply(fasta_ls, get_ST_variant_call)
Ecoli_SNV_long <- map_dfr(var_call_dist_ls, 2)

# transmission SNV cutoff
cutoff <- 5 # specify SNV cutoff of interest
Ecoli_SNV_long <- Ecoli_SNV_long  %>%
  mutate(transmission = ifelse(dist <=cutoff, 1,0)) %>%
  filter(X1 %in% meta$Sample & X2 %in% meta$Sample)

```

# meta data with demographic information of participants
```{r}
# subsetting
meta <- readRDS( "data/meta.rds")
```


```{r}
# merge and make sure the two data frames are in the same order
Ecoli_meta_long1 <- merge(Ecoli_SNV_long , meta , by.x ="X1" ,by.y = "Sample", all.x = TRUE) %>%
  arrange(X1, X2)
Ecoli_meta_long2 <- merge(Ecoli_SNV_long , meta , by.x ="X2" ,by.y = "Sample", all.x = TRUE) %>%
  arrange(X1, X2)

match_mat<- Ecoli_meta_long1[,7:13]== Ecoli_meta_long2[,7:13] %>% as.matrix()
match_mat <- ifelse(match_mat, as.matrix(Ecoli_meta_long1[,7:13]), "No")

Ecoli_meta_match <- cbind(Ecoli_meta_long1[,1:6],match_mat)

# rename some of the variables
Ecoli_meta_match <- Ecoli_meta_match %>%
  mutate(hhid_match = ifelse(hhid!="No","Yes",hhid),
         social_no_hh_match = case_when(social!="No" & is.na(hhid)~"Yes",
                                        social!="No" & hhid=="No"~"Yes",
                                        TRUE ~"No")) %>%
  
  filter(!is.na(lockdown))

```

```{r}
# unorder variables, and set refernece value at 'No'
Ecoli_meta_match[,6:ncol(Ecoli_meta_match)] <- apply(Ecoli_meta_match[,6:ncol(Ecoli_meta_match)], 2, function(x){
  x <- factor(x, ordered = FALSE)
  if ("No" %in% x){
    x <- relevel(x, ref = "No")
  }
})
```

# pre-post lockdown model

# subsetting pre and post models
```{r}
pre_Ecoli_meta_all <- Ecoli_meta_match %>%
  filter(lockdown=="pre")

post_Ecoli_meta_all <- Ecoli_meta_match %>%
  filter(lockdown=="post")
```


# variables to test for univariate models
```{r}
# create covar
pre_covar <- colnames(Ecoli_meta_match[6:ncol(Ecoli_meta_match)])
pre_covar <- pre_covar[pre_covar!="lockdown"]
remove_var <- c("hhid","social")
pre_covar <- pre_covar[!pre_covar %in% remove_var]

# create covar
post_covar <- colnames(Ecoli_meta_match[6:ncol(Ecoli_meta_match)])
post_covar <- post_covar[post_covar!="lockdown"]
remove_var <- c("hhid","social")
post_covar <- post_covar[!post_covar %in% remove_var]
```

# fit models
```{r}

# variables 
lockdown_var <- c("hhid_match","location","participant_type", "region","social_no_hh_match")

# for all the pre-covid variables
pre_model_df_all <- data.frame()
for (var in lockdown_var){
  if(var=="hhid_match"){
    new_df <- fit_mixed_log_model(df = pre_Ecoli_meta_all, dep_var = "transmission", indep_var = var)
  }
 else{
   subdf <- pre_Ecoli_meta_all %>%
     filter(hhid_match!="Yes"| is.na(hhid_match))
   new_df <- fit_mixed_log_model(df = subdf, dep_var = "transmission", indep_var = var)
 }
  pre_model_df_all <- rbind(pre_model_df_all, new_df)
}

post_model_df_all <- data.frame()
for (var in lockdown_var){
  if(var=="hhid_match"){
    new_df <- fit_mixed_log_model(df = post_Ecoli_meta_all, dep_var = "transmission", indep_var = var)
  }
  else{
    subdf <- post_Ecoli_meta_all %>%
      filter(hhid_match!="Yes"| is.na(hhid_match))
    new_df <- fit_mixed_log_model(df = subdf, dep_var = "transmission", indep_var = var)
  }
  
  post_model_df_all <- rbind(post_model_df_all, new_df)
}

```
## Compile fit results
```{r}
Ecoli_pre_df <- Ecoli_meta_match %>%
  filter(lockdown=="pre")


# plot stats without 1722
pre_summary <- create_pair_summary(stats_df = pre_model_df_all, pairiwise_var_df = pre_Ecoli_meta_all, var_v = lockdown_var)
post_summary <- create_pair_summary(stats_df = post_model_df_all, pairiwise_var_df = post_Ecoli_meta_all, var_v = lockdown_var)

lockdown_df <- pre_summary[[2]] %>%
  mutate(Lockdown = "Pre-Lockdown") %>%
  merge(pre_summary[[1]][,c("group","variables","p.value","odds", "upperCI","lowerCI")],by = c("group","variables")) %>%
  rbind(post_summary[[2]] %>% mutate(Lockdown = "Post-Lockdown") %>% merge(post_summary[[1]][,c("group","variables","p.value","odds", "upperCI","lowerCI")],by = c("group","variables")))

lockdown_df <- lockdown_df%>% distinct() %>%
  filter(!is.na(p.value)|variables=="No")

lockdown_df <- lockdown_df %>%
  group_by(group, Lockdown,Pair_SNV_bool) %>%
  mutate(uniq_var_n = length(unique(variables))) %>%
  filter(uniq_var_n>1 )%>%
  #group_by(group,  Lockdown) %>%
  mutate(p_adjust = p.adjust(p.value, method = "bonferroni"),
         FDR = p.adjust(p.value, method ="BH"))

# relevel the variable for plotting
lockdown_df$Lockdown <- factor(lockdown_df$Lockdown, levels=c("Pre-Lockdown","Post-Lockdown"))
```

# plot results
```{r}
lockdown_var <- c("age1", "hhid_match","location","participant_type", "region","social_no_hh_match")
lockdown_df$variables<- factor(lockdown_df$variables, levels=c("No","Yes","Bokaa Clinic","Borakalalo Clinic","Boseja Clinic","Julia Molefhe Clinic","Nkoyaphiri Clinic","Phuthadikobo Clinic","Princes Marina Hospital","Scottish Livingstone Referral Hospital","Deborah Retief Memorial Hospital","Gaborone","Clinic patient","Mochudi","Molepolele","Community adult","Community child","Hospital patient","Community/Clinic","Hospital","age <= 5","age 6 to 18","age > 18"))
g <- lockdown_df %>%
  group_by(group, variables,Lockdown) %>%
  mutate(prop = Freq/sum(Freq)) %>%
  filter(Pair_SNV_bool==1) %>%
  mutate(group1 = group,
         group1 = case_when(group=="age1"~"age",
                           group=="hhid_match"~"household",
                           group =="participant_type"~"participant type",
                           group =="social_no_hh_match"~"social network",
                           TRUE~group),
         facility = case_when(variables == "Bokaa Clinic"~ "Clinic A",
                              variables == "Borakalalo Clinic"~"Clinic B",
                              variables == "Boseja Clinic" ~"Clinic C",
                              variables == "Deborah Retief Memorial Hospital"~ "Hospital A",
                              variables == "Julia Molefhe Clinic" ~ "Clinic D",
                              variables == "Nkoyaphiri Clinic" ~ "Clinic E",
                              variables == "Phuthadikobo Clinic" ~ "Clinic F",
                              variables == "Princes Marina Hospital" ~ "Hospital B",
                              variables == "Scottish Livingstone Referral Hospital" ~ "Hospital C",
                              TRUE ~variables)) %>% 
  mutate(`p<0.05` = ifelse(FDR<0.05 & odds >=1,"*","")) %>%
  mutate(`Shared risk` = ifelse(variables=="No","No","Yes")) %>%
  filter(group!="participant_type1") 
g$facility <- factor(g$facility, levels = c("No","Yes","Clinic A","Clinic B","Clinic C","Clinic D","Clinic E","Clinic F","Hospital A","Hospital B","Hospital C","Gaborone","Clinic patient","Mochudi","Molepolele","Community adult","Community child","Hospital patient","Community/Clinic","Hospital","age <= 5","age 6 to 18","age > 18"))
g %>%
  ggplot() + geom_col(aes(x = variables ,y= prop*100, fill = `Shared risk`)) +geom_text(aes(x = variables,label = `p<0.05`),y = 1, size = 7)  + labs( y = "% Transmission pairs with shared demographics",x = "Demographics")+ 
scale_fill_viridis_d(name = "Shared\ndemographics", label =c("0"="No","1"="Yes")) +theme_void()+ theme_bw() + theme(axis.text.x = element_text(angle = 40,hjust = 1), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank()) + facet_grid(Lockdown~group1, scales = "free") # + ggh4x::facet_grid2(Lockdown~group,scales = "free_x", independent = "x")
#write_xlsx(lockdown_df,"~/Dropbox (University of Michigan)/IMPALA-2/Meta-data/mixed_effect_model_output.xlsx")
#ggsave("/Users/tifwan/Dropbox (University of Michigan)/IMPALA-2/Manuscripts/Decriptive genomic epi paper/Figures/variant_lockdown/2024_12_20_lockdown_risk.pdf", width =10)
#ggsave("/Users/tifwan/University of Michigan Dropbox/Tiffany Wan/IMPALA-2/Manuscripts/Decriptive genomic epi paper/2025_04_26/figure_5a.pdf", width = 12)
```
